### ISSUE TITLE
Gruppen-Monitor verbleibt im Polling-modus

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-frontend#230]
# Fehlerbeschreibung

Schultest 19.10, 7:45: Testleitugs-Konsole (laut Serverlogs) offenbar im Reconnect/Polling-Modus. Nicht aber die Teilnehmer, dort hat die Websocket-Verbindung gut funktioniert. Grund unbekannt; vermutlich hat trotzdem alles funktioniert, es gab keinen Anruf.

User-Agent war: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"

User-Agent der Schüler war: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36`
`

Konsole wirft diese Fehler (aber keine anderen):
```
testcenter-backend                 | localhost:80 172.25.0.2 - - [19/Oct/2020:06:36:44 +0000] "PATCH /test/699/state HTTP/1.1" 200 566 "https://www.iqb-testcenter.de/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
testcenter-backend                 | localhost:80 172.25.0.2 - - [19/Oct/2020:06:36:44 +0000] "PATCH /test/701/unit/ER553r/restorepoint HTTP/1.1" 200 585 "https://www.iqb-testcenter.de/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
testcenter-broadcasting-service    | error caught:  NotFoundException [Error]: Cannot GET /public/84e905c797ad0f4c3897e798a545aa8e
testcenter-broadcasting-service    |     at callback (/app/node_modules/@nestjs/core/router/routes-resolver.js:46:19)
testcenter-broadcasting-service    |     at /app/node_modules/@nestjs/core/router/router-proxy.js:9:23
testcenter-broadcasting-service    |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
testcenter-broadcasting-service    |     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
testcenter-broadcasting-service    |     at /app/node_modules/express/lib/router/index.js:284:7
testcenter-broadcasting-service    |     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
testcenter-broadcasting-service    |     at next (/app/node_modules/express/lib/router/index.js:275:10)
testcenter-broadcasting-service    |     at urlencodedParser (/app/node_modules/body-parser/lib/types/urlencoded.js:91:7)
testcenter-broadcasting-service    |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
testcenter-broadcasting-service    |     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13) {
testcenter-broadcasting-service    |   response: {
testcenter-broadcasting-service    |     statusCode: 404,
testcenter-broadcasting-service    |     message: 'Cannot GET /public/84e905c797ad0f4c3897e798a545aa8e',
testcenter-broadcasting-service    |     error: 'Not Found'
testcenter-broadcasting-service    |   },
testcenter-broadcasting-service    |   status: 404
testcenter-broadcasting-service    | }
testcenter-backend                 | localhost
```

# Kontext
**Server**: https://www.iqb-testcenter.de/

**Frontend-Version**: 6.3.1

**Backend-Version**: 7.4.0

**Testdaten (player etc.)**: Testleitungskonsole-Erprobung

**Modus**: ho

**Browser**: Vermutlich Safari

**Comment by paflov** [comment]
Unklar, nicht zu rekonstruieren.
